// ─────────────────────────────────────────────────────────────────────────────
// pharmacyData.js
//
// TWO-TIER data model, replacing the earlier flattened design:
//
//   Medicine (the "Product" tier) — one record per distinct branded
//   product: brand name + generic name + strength + dosage form +
//   manufacturer together define identity. "Crocin 650" and "Crocin 500"
//   are two separate Medicine records, not one record with a
//   batch-varying strength — strength is baked into what was
//   manufactured, not decided per-shipment.
//
//   Batch — one record per physical shipment of a Medicine, referencing
//   it via medicineId. Multiple batches of the same Medicine can be
//   Active at once (e.g. one lot expiring in August, another in
//   December) — FEFO dispensing depends on being able to tell them
//   apart, which a flattened single-row-per-medicine model cannot do.
//
// Quantity, batch number, expiry date, and cost/MRP paid THIS shipment
// all live on Batch, never on Medicine. A Medicine with zero Active
// batches has zero stock — that's a real, valid state (a catalogued drug
// currently out of stock), not a data error.
// ─────────────────────────────────────────────────────────────────────────────

export const SCHEDULE_CONFIG = {
  OTC: { color: "#059669", bg: "#ecfdf5" },
  H: { color: "#2563eb", bg: "#eff6ff" },
  H1: { color: "#d97706", bg: "#fffbeb" },
  X: { color: "#dc2626", bg: "#fef2f2" },
};

export const STOCK_STATUS_CONFIG = {
  "In Stock": { color: "#059669" },
  "Low Stock": { color: "#d97706", bg: "#fffbeb" },
  "Out of Stock": { color: "#dc2626", bg: "#fef2f2" },
};

export const EXPIRY_STATUS_CONFIG = {
  Good: { color: "#475569" },
  "Expiring Soon": { color: "#d97706", bg: "#fffbeb" },
  Expired: { color: "#dc2626", bg: "#fef2f2" },
  "No Active Batches": { color: "#94a3b8" },
};

export const BATCH_STATUS_CONFIG = {
  Active: { color: "#059669", bg: "#ecfdf5" },
  Removed: { color: "#64748b", bg: "#f1f5f9" },
  Disposed: { color: "#dc2626", bg: "#fef2f2" },
};

// Urgency tiers for Expiry Alerts — "Critical" sits visually between
// Expired (red) and Warning (amber) as a distinct orange, so all three
// severities read as genuinely different at a glance, not shades of the
// same color.
export const EXPIRY_TIER_CONFIG = {
  Expired: { color: "#dc2626", bg: "#fef2f2" },
  Critical: { color: "#ea580c", bg: "#fff7ed" },
  Warning: { color: "#d97706", bg: "#fffbeb" },
};

// Manual adjustment types — all DECREASE stock except Correction, which
// can go either direction (a physical recount might find MORE stock
// than recorded, e.g. a prior miscount, not just less).
//
//   Damage      — physically broken/contaminated, unsellable.
//   Loss        — missing with no known cause (theft, misplacement).
//   Correction  — reconciling recorded quantity against a physical count.
//   Transfer    — moved to a different pharmacy location/branch, leaving
//                 this one's stock (recorded as a decrease here; the
//                 receiving location is outside this project's scope).
export const ADJUSTMENT_TYPE_CONFIG = {
  Damage: { color: "#dc2626", bg: "#fef2f2", direction: "decrease" },
  Loss: { color: "#dc2626", bg: "#fef2f2", direction: "decrease" },
  Correction: { color: "#2563eb", bg: "#eff6ff", direction: "either" },
  Transfer: { color: "#d97706", bg: "#fffbeb", direction: "decrease" },
};

export const CATEGORIES = [
  "Analgesic",
  "Antibiotic",
  "Antacid / PPI",
  "Antihistamine",
  "Antidiabetic",
  "Antihypertensive",
  "Lipid-Lowering",
  "Respiratory",
  "Antiemetic",
  "Antiseptic / Topical",
  "Vitamin & Supplement",
  "Rehydration",
  "Anxiolytic",
];

export const DOSAGE_FORMS = [
  "Tablet",
  "Capsule",
  "Syrup",
  "Injection",
  "Ointment / Gel",
  "Inhaler",
  "Sachet / Powder",
  "Drops",
];

export const STORAGE_CONDITIONS = [
  "Room Temperature",
  "Refrigerated (2-8°C)",
  "Cool & Dry, Secure Storage",
];

export const SHELF_LOCATIONS = [
  "Aisle A - Shelf 1",
  "Aisle A - Shelf 2",
  "Aisle A - Shelf 3",
  "Aisle B - Shelf 1",
  "Aisle B - Shelf 2",
  "Aisle B - Shelf 3",
  "Cold Storage Unit 1",
  "Cold Storage Unit 2",
  "Controlled Substances Cabinet",
];

export const GST_SLABS = [0, 5, 12, 18, 28];

export const SUPPLIERS = [
  "MedPlus Distributors",
  "Apollo Pharmacy Wholesale",
  "Zydus Healthcare Supply Chain",
  "Sun Pharma Direct",
  "Cipla Regional Distributor",
  "Wellness Forever Supply Co.",
];

// ── Medicine master records (Product tier) ────────────────────────────────────
export const initialMedicines = [
  {
    id: "M-001",
    brandName: "Crocin 650",
    genericName: "Paracetamol",
    strength: "650mg",
    category: "Analgesic",
    dosageForm: "Tablet",
    manufacturer: "GSK",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    reorderLevel: 200,
  },
  {
    id: "M-002",
    brandName: "Dolo 650",
    genericName: "Paracetamol",
    strength: "650mg",
    category: "Analgesic",
    dosageForm: "Tablet",
    manufacturer: "Micro Labs",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    reorderLevel: 200,
  },
  {
    id: "M-003",
    brandName: "Brufen 400",
    genericName: "Ibuprofen",
    strength: "400mg",
    category: "Analgesic",
    dosageForm: "Tablet",
    manufacturer: "Abbott",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    reorderLevel: 100,
  },
  {
    id: "M-004",
    brandName: "Mox 500",
    genericName: "Amoxicillin",
    strength: "500mg",
    category: "Antibiotic",
    dosageForm: "Capsule",
    manufacturer: "Sun Pharma",
    schedule: "H1",
    storageCondition: "Room Temperature",
    reorderLevel: 150,
  },
  {
    id: "M-005",
    brandName: "Azithral 500",
    genericName: "Azithromycin",
    strength: "500mg",
    category: "Antibiotic",
    dosageForm: "Tablet",
    manufacturer: "Alembic",
    schedule: "H1",
    storageCondition: "Room Temperature",
    reorderLevel: 100,
  },
  {
    id: "M-006",
    brandName: "Cifran 500",
    genericName: "Ciprofloxacin",
    strength: "500mg",
    category: "Antibiotic",
    dosageForm: "Tablet",
    manufacturer: "Ranbaxy",
    schedule: "H1",
    storageCondition: "Room Temperature",
    reorderLevel: 100,
  },
  {
    id: "M-007",
    brandName: "Glycomet 500",
    genericName: "Metformin",
    strength: "500mg",
    category: "Antidiabetic",
    dosageForm: "Tablet",
    manufacturer: "USV",
    schedule: "H",
    storageCondition: "Room Temperature",
    reorderLevel: 150,
  },
  {
    id: "M-008",
    brandName: "Amlopres 5",
    genericName: "Amlodipine",
    strength: "5mg",
    category: "Antihypertensive",
    dosageForm: "Tablet",
    manufacturer: "Cipla",
    schedule: "H",
    storageCondition: "Room Temperature",
    reorderLevel: 100,
  },
  {
    id: "M-009",
    brandName: "Atorva 10",
    genericName: "Atorvastatin",
    strength: "10mg",
    category: "Lipid-Lowering",
    dosageForm: "Tablet",
    manufacturer: "Zydus",
    schedule: "H",
    storageCondition: "Room Temperature",
    reorderLevel: 100,
  },
  {
    id: "M-010",
    brandName: "Omez 20",
    genericName: "Omeprazole",
    strength: "20mg",
    category: "Antacid / PPI",
    dosageForm: "Capsule",
    manufacturer: "Dr. Reddy's",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    reorderLevel: 150,
  },
  {
    id: "M-011",
    brandName: "Pan 40",
    genericName: "Pantoprazole",
    strength: "40mg",
    category: "Antacid / PPI",
    dosageForm: "Tablet",
    manufacturer: "Alkem",
    schedule: "H",
    storageCondition: "Room Temperature",
    reorderLevel: 100,
  },
  {
    id: "M-012",
    brandName: "Alerid 10",
    genericName: "Cetirizine",
    strength: "10mg",
    category: "Antihistamine",
    dosageForm: "Tablet",
    manufacturer: "Cipla",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    reorderLevel: 150,
  },
  {
    id: "M-013",
    brandName: "Levocet 5",
    genericName: "Levocetirizine",
    strength: "5mg",
    category: "Antihistamine",
    dosageForm: "Tablet",
    manufacturer: "UCB",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    reorderLevel: 100,
  },
  {
    id: "M-014",
    brandName: "Asthalin Inhaler",
    genericName: "Salbutamol",
    strength: "100mcg/dose",
    category: "Respiratory",
    dosageForm: "Inhaler",
    manufacturer: "Cipla",
    schedule: "H",
    storageCondition: "Room Temperature",
    reorderLevel: 40,
  },
  {
    id: "M-015",
    brandName: "Benadryl Syrup",
    genericName: "Diphenhydramine",
    strength: "100ml",
    category: "Respiratory",
    dosageForm: "Syrup",
    manufacturer: "Johnson & Johnson",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    reorderLevel: 50,
  },
  {
    id: "M-016",
    brandName: "Electral",
    genericName: "Oral Rehydration Salts",
    strength: "21.8g sachet",
    category: "Rehydration",
    dosageForm: "Sachet / Powder",
    manufacturer: "FDC",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    reorderLevel: 200,
  },
  {
    id: "M-017",
    brandName: "Lantus",
    genericName: "Insulin Glargine",
    strength: "100 IU/ml",
    category: "Antidiabetic",
    dosageForm: "Injection",
    manufacturer: "Sanofi",
    schedule: "H",
    storageCondition: "Refrigerated (2-8°C)",
    reorderLevel: 20,
  },
  {
    id: "M-018",
    brandName: "Voveran Gel",
    genericName: "Diclofenac",
    strength: "1%",
    category: "Antiseptic / Topical",
    dosageForm: "Ointment / Gel",
    manufacturer: "Novartis",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    reorderLevel: 80,
  },
  {
    id: "M-019",
    brandName: "Betadine",
    genericName: "Povidone Iodine",
    strength: "5%",
    category: "Antiseptic / Topical",
    dosageForm: "Ointment / Gel",
    manufacturer: "Win-Medicare",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    reorderLevel: 60,
  },
  {
    id: "M-020",
    brandName: "Calcirol Sachet",
    genericName: "Vitamin D3",
    strength: "60,000 IU",
    category: "Vitamin & Supplement",
    dosageForm: "Sachet / Powder",
    manufacturer: "Cadila",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    reorderLevel: 100,
  },
  {
    id: "M-021",
    brandName: "Revital",
    genericName: "Multivitamin & Minerals",
    strength: "—",
    category: "Vitamin & Supplement",
    dosageForm: "Capsule",
    manufacturer: "Ranbaxy",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    reorderLevel: 100,
  },
  {
    id: "M-022",
    brandName: "Fefol",
    genericName: "Iron + Folic Acid",
    strength: "—",
    category: "Vitamin & Supplement",
    dosageForm: "Tablet",
    manufacturer: "Pfizer",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    reorderLevel: 100,
  },
  {
    id: "M-023",
    brandName: "Domstal",
    genericName: "Domperidone",
    strength: "10mg",
    category: "Antiemetic",
    dosageForm: "Tablet",
    manufacturer: "Torrent",
    schedule: "H",
    storageCondition: "Room Temperature",
    reorderLevel: 80,
  },
  {
    id: "M-024",
    brandName: "Emeset",
    genericName: "Ondansetron",
    strength: "4mg",
    category: "Antiemetic",
    dosageForm: "Tablet",
    manufacturer: "Cipla",
    schedule: "H",
    storageCondition: "Room Temperature",
    reorderLevel: 60,
  },
  {
    id: "M-025",
    brandName: "Ultracet",
    genericName: "Tramadol + Paracetamol",
    strength: "37.5mg/325mg",
    category: "Analgesic",
    dosageForm: "Tablet",
    manufacturer: "Johnson & Johnson",
    schedule: "H1",
    storageCondition: "Room Temperature",
    reorderLevel: 50,
  },
  {
    id: "M-026",
    brandName: "Morcontin 10",
    genericName: "Morphine Sulfate",
    strength: "10mg",
    category: "Analgesic",
    dosageForm: "Tablet",
    manufacturer: "Mundipharma",
    schedule: "X",
    storageCondition: "Cool & Dry, Secure Storage",
    reorderLevel: 15,
  },
  {
    id: "M-027",
    brandName: "Alprax 0.25",
    genericName: "Alprazolam",
    strength: "0.25mg",
    category: "Anxiolytic",
    dosageForm: "Tablet",
    manufacturer: "Torrent",
    schedule: "X",
    storageCondition: "Cool & Dry, Secure Storage",
    reorderLevel: 40,
  },
];

// ── Batches (Shipment tier) — each references a medicineId above ──────────────
// Several medicines deliberately carry 2 Active batches with different
// expiry dates, to demonstrate real FEFO-relevant data (Crocin 650,
// Metformin). A few medicines deliberately have ZERO batches (Revital,
// Ondansetron) — a catalogued product currently out of stock, a valid
// and important state the old flattened model could not represent.
export const initialBatches = [
  {
    id: "B-001",
    medicineId: "M-001",
    batchNumber: "CR2547",
    quantity: 850,
    unitCost: 1.2,
    mrp: 1.8,
    expiryDate: "2027-08-15",
    shelfLocation: "Aisle A - Shelf 1",
    supplier: "MedPlus Distributors",
    invoiceNumber: "INV-40012",
    purchaseDate: "2026-02-10",
    status: "Active",
  },
  {
    id: "B-002",
    medicineId: "M-001",
    batchNumber: "CR2601",
    quantity: 200,
    unitCost: 1.25,
    mrp: 1.8,
    expiryDate: "2026-09-30",
    shelfLocation: "Aisle A - Shelf 2",
    supplier: "MedPlus Distributors",
    invoiceNumber: "INV-41207",
    purchaseDate: "2026-05-02",
    status: "Active",
  },
  {
    id: "B-003",
    medicineId: "M-002",
    batchNumber: "DL3321",
    quantity: 620,
    unitCost: 1.1,
    mrp: 1.7,
    expiryDate: "2027-11-10",
    shelfLocation: "Aisle A - Shelf 1",
    supplier: "Sun Pharma Direct",
    invoiceNumber: "INV-40088",
    purchaseDate: "2026-02-18",
    status: "Active",
  },
  {
    id: "B-004",
    medicineId: "M-003",
    batchNumber: "BR8842",
    quantity: 45,
    unitCost: 2.5,
    mrp: 3.8,
    expiryDate: "2026-12-20",
    shelfLocation: "Aisle A - Shelf 2",
    supplier: "Apollo Pharmacy Wholesale",
    invoiceNumber: "INV-39950",
    purchaseDate: "2026-01-22",
    status: "Active",
  },
  {
    id: "B-005",
    medicineId: "M-005",
    batchNumber: "AZ4456",
    quantity: 90,
    unitCost: 18.0,
    mrp: 26.0,
    expiryDate: "2026-08-05",
    shelfLocation: "Aisle B - Shelf 1",
    supplier: "Cipla Regional Distributor",
    invoiceNumber: "INV-40501",
    purchaseDate: "2026-03-11",
    status: "Active",
  },
  {
    id: "B-006",
    medicineId: "M-006",
    batchNumber: "CF7723",
    quantity: 310,
    unitCost: 8.5,
    mrp: 12.0,
    expiryDate: "2027-05-18",
    shelfLocation: "Aisle B - Shelf 1",
    supplier: "Zydus Healthcare Supply Chain",
    invoiceNumber: "INV-40620",
    purchaseDate: "2026-03-20",
    status: "Active",
  },
  {
    id: "B-007",
    medicineId: "M-007",
    batchNumber: "GM5612",
    quantity: 280,
    unitCost: 1.8,
    mrp: 2.6,
    expiryDate: "2027-09-30",
    shelfLocation: "Aisle B - Shelf 2",
    supplier: "MedPlus Distributors",
    invoiceNumber: "INV-40712",
    purchaseDate: "2026-04-01",
    status: "Active",
  },
  {
    id: "B-008",
    medicineId: "M-007",
    batchNumber: "GM5688",
    quantity: 200,
    unitCost: 1.85,
    mrp: 2.6,
    expiryDate: "2026-11-15",
    shelfLocation: "Aisle B - Shelf 3",
    supplier: "MedPlus Distributors",
    invoiceNumber: "INV-41340",
    purchaseDate: "2026-05-15",
    status: "Active",
  },
  {
    id: "B-009",
    medicineId: "M-008",
    batchNumber: "AM9981",
    quantity: 275,
    unitCost: 2.1,
    mrp: 3.0,
    expiryDate: "2027-03-22",
    shelfLocation: "Aisle B - Shelf 2",
    supplier: "Cipla Regional Distributor",
    invoiceNumber: "INV-40145",
    purchaseDate: "2026-02-14",
    status: "Active",
  },
  {
    id: "B-010",
    medicineId: "M-009",
    batchNumber: "AT4470",
    quantity: 198,
    unitCost: 4.5,
    mrp: 6.8,
    expiryDate: "2026-07-19",
    shelfLocation: "Aisle B - Shelf 3",
    supplier: "Zydus Healthcare Supply Chain",
    invoiceNumber: "INV-39887",
    purchaseDate: "2026-01-19",
    status: "Active",
  },
  {
    id: "B-011",
    medicineId: "M-010",
    batchNumber: "OM3320",
    quantity: 410,
    unitCost: 3.2,
    mrp: 4.9,
    expiryDate: "2027-01-12",
    shelfLocation: "Aisle A - Shelf 3",
    supplier: "MedPlus Distributors",
    invoiceNumber: "INV-40233",
    purchaseDate: "2026-02-25",
    status: "Active",
  },
  {
    id: "B-012",
    medicineId: "M-011",
    batchNumber: "PN6671",
    quantity: 22,
    unitCost: 5.0,
    mrp: 7.5,
    expiryDate: "2027-04-08",
    shelfLocation: "Aisle A - Shelf 3",
    supplier: "Apollo Pharmacy Wholesale",
    invoiceNumber: "INV-40399",
    purchaseDate: "2026-03-02",
    status: "Active",
  },
  {
    id: "B-013",
    medicineId: "M-012",
    batchNumber: "CT2280",
    quantity: 560,
    unitCost: 0.9,
    mrp: 1.5,
    expiryDate: "2027-10-25",
    shelfLocation: "Aisle A - Shelf 2",
    supplier: "Cipla Regional Distributor",
    invoiceNumber: "INV-40890",
    purchaseDate: "2026-04-10",
    status: "Active",
  },
  {
    id: "B-014",
    medicineId: "M-013",
    batchNumber: "LV5543",
    quantity: 0,
    unitCost: 1.5,
    mrp: 2.3,
    expiryDate: "2026-09-14",
    shelfLocation: "Aisle A - Shelf 2",
    supplier: "MedPlus Distributors",
    invoiceNumber: "INV-39412",
    purchaseDate: "2025-12-05",
    status: "Active",
  },
  {
    id: "B-015",
    medicineId: "M-014",
    batchNumber: "AS7790",
    quantity: 38,
    unitCost: 95.0,
    mrp: 135.0,
    expiryDate: "2026-10-30",
    shelfLocation: "Aisle B - Shelf 1",
    supplier: "Cipla Regional Distributor",
    invoiceNumber: "INV-40456",
    purchaseDate: "2026-03-08",
    status: "Active",
  },
  {
    id: "B-016",
    medicineId: "M-015",
    batchNumber: "BD1123",
    quantity: 130,
    unitCost: 45.0,
    mrp: 68.0,
    expiryDate: "2026-06-10",
    shelfLocation: "Aisle B - Shelf 1",
    supplier: "Wellness Forever Supply Co.",
    invoiceNumber: "INV-39299",
    purchaseDate: "2025-11-28",
    status: "Active",
  },
  {
    id: "B-017",
    medicineId: "M-016",
    batchNumber: "EL9012",
    quantity: 920,
    unitCost: 8.0,
    mrp: 12.0,
    expiryDate: "2028-01-01",
    shelfLocation: "Aisle A - Shelf 3",
    supplier: "MedPlus Distributors",
    invoiceNumber: "INV-41005",
    purchaseDate: "2026-04-22",
    status: "Active",
  },
  {
    id: "B-018",
    medicineId: "M-017",
    batchNumber: "LN3345",
    quantity: 18,
    unitCost: 410.0,
    mrp: 580.0,
    expiryDate: "2026-08-31",
    shelfLocation: "Cold Storage Unit 1",
    supplier: "Sun Pharma Direct",
    invoiceNumber: "INV-40567",
    purchaseDate: "2026-03-15",
    status: "Active",
  },
  {
    id: "B-019",
    medicineId: "M-018",
    batchNumber: "VV4456",
    quantity: 205,
    unitCost: 38.0,
    mrp: 55.0,
    expiryDate: "2027-06-15",
    shelfLocation: "Aisle B - Shelf 2",
    supplier: "Zydus Healthcare Supply Chain",
    invoiceNumber: "INV-40789",
    purchaseDate: "2026-04-05",
    status: "Active",
  },
  {
    id: "B-020",
    medicineId: "M-019",
    batchNumber: "BT7781",
    quantity: 165,
    unitCost: 28.0,
    mrp: 42.0,
    expiryDate: "2027-09-01",
    shelfLocation: "Aisle B - Shelf 2",
    supplier: "Wellness Forever Supply Co.",
    invoiceNumber: "INV-40912",
    purchaseDate: "2026-04-14",
    status: "Active",
  },
  {
    id: "B-021",
    medicineId: "M-020",
    batchNumber: "CL2290",
    quantity: 340,
    unitCost: 22.0,
    mrp: 32.0,
    expiryDate: "2027-12-20",
    shelfLocation: "Aisle A - Shelf 3",
    supplier: "Cipla Regional Distributor",
    invoiceNumber: "INV-41102",
    purchaseDate: "2026-04-28",
    status: "Active",
  },
  {
    id: "B-022",
    medicineId: "M-022",
    batchNumber: "FF3398",
    quantity: 290,
    unitCost: 1.6,
    mrp: 2.4,
    expiryDate: "2026-07-05",
    shelfLocation: "Aisle A - Shelf 3",
    supplier: "MedPlus Distributors",
    invoiceNumber: "INV-39678",
    purchaseDate: "2026-01-08",
    status: "Active",
  },
  {
    id: "B-023",
    medicineId: "M-023",
    batchNumber: "DM6612",
    quantity: 175,
    unitCost: 2.0,
    mrp: 3.0,
    expiryDate: "2027-05-30",
    shelfLocation: "Aisle B - Shelf 3",
    supplier: "Apollo Pharmacy Wholesale",
    invoiceNumber: "INV-40678",
    purchaseDate: "2026-03-25",
    status: "Active",
  },
  {
    id: "B-024",
    medicineId: "M-025",
    batchNumber: "UL2245",
    quantity: 64,
    unitCost: 6.0,
    mrp: 9.0,
    expiryDate: "2027-01-18",
    shelfLocation: "Aisle A - Shelf 1",
    supplier: "Sun Pharma Direct",
    invoiceNumber: "INV-40289",
    purchaseDate: "2026-02-27",
    status: "Active",
  },
  {
    id: "B-025",
    medicineId: "M-026",
    batchNumber: "MR1102",
    quantity: 12,
    unitCost: 22.0,
    mrp: 32.0,
    expiryDate: "2027-08-22",
    shelfLocation: "Controlled Substances Cabinet",
    supplier: "Sun Pharma Direct",
    invoiceNumber: "INV-40023",
    purchaseDate: "2026-02-11",
    status: "Active",
  },
  {
    id: "B-026",
    medicineId: "M-027",
    batchNumber: "AP3367",
    quantity: 55,
    unitCost: 1.8,
    mrp: 2.7,
    expiryDate: "2027-03-10",
    shelfLocation: "Controlled Substances Cabinet",
    supplier: "Zydus Healthcare Supply Chain",
    invoiceNumber: "INV-40178",
    purchaseDate: "2026-02-19",
    status: "Active",
  },
  // M-004 (Amoxicillin), M-021 (Revital), and M-024 (Ondansetron) deliberately
  // have zero batches — genuinely out-of-stock catalogued products.
];
