// ─────────────────────────────────────────────────────────────────────────────
// pharmacyData.js
//
// Pharmacy medicine inventory — the primary data source for the Pharmacy
// module, following the same pattern as opdData.js/ipdData.js.
//
// SCHEDULE classification follows India's real four-tier drug-control
// system (Drugs and Cosmetics Rules):
//   OTC — no prescription needed. Example: Paracetamol, antacids, ORS.
//   H   — prescription required, no special register. Example: most
//         antihypertensives, antidiabetics.
//   H1  — prescription required AND the pharmacist must maintain a
//         dispensing register (patient/doctor details recorded) —
//         introduced specifically to curb antibiotic misuse and
//         unsupervised sale of habit-forming drugs. Example: many
//         antibiotics.
//   X   — narcotic/psychotropic substances, special license to stock,
//         records retained long-term. Example: morphine, certain
//         anxiolytics/sedatives.
//
// Colors deliberately reuse this app's existing semantic palette (green =
// fine, blue = standard, amber = caution, red = critical/restricted) —
// the same meaning these colors already carry everywhere else in the app
// (patient/appointment/admission statuses), not a new color language.
// ─────────────────────────────────────────────────────────────────────────────

export const SCHEDULE_CONFIG = {
  OTC: { color: "#059669", bg: "#ecfdf5" },
  H: { color: "#2563eb", bg: "#eff6ff" },
  H1: { color: "#d97706", bg: "#fffbeb" },
  X: { color: "#dc2626", bg: "#fef2f2" },
};

export const STOCK_STATUS_CONFIG = {
  "In Stock": { color: "#059669" },
  "Low Stock": { color: "#d97706", bg: "#fffbeb" },
  "Out of Stock": { color: "#dc2626", bg: "#fef2f2" },
};

export const EXPIRY_STATUS_CONFIG = {
  Good: { color: "#475569" },
  "Expiring Soon": { color: "#d97706", bg: "#fffbeb" },
  Expired: { color: "#dc2626", bg: "#fef2f2" },
};

// Canonical lists — exported so tomorrow's Add Medicine Form reuses the
// exact same options rather than inventing a second, slightly different
// list.
export const CATEGORIES = [
  "Analgesic",
  "Antibiotic",
  "Antacid / PPI",
  "Antihistamine",
  "Antidiabetic",
  "Antihypertensive",
  "Lipid-Lowering",
  "Respiratory",
  "Antiemetic",
  "Antiseptic / Topical",
  "Vitamin & Supplement",
  "Rehydration",
  "Anxiolytic",
];

export const DOSAGE_FORMS = [
  "Tablet",
  "Capsule",
  "Syrup",
  "Injection",
  "Ointment / Gel",
  "Inhaler",
  "Sachet / Powder",
  "Drops",
];

export const STORAGE_CONDITIONS = [
  "Room Temperature",
  "Refrigerated (2-8°C)",
  "Cool & Dry, Secure Storage",
];

export const initialMedicines = [
  {
    id: "MED-001",
    brandName: "Crocin 650",
    genericName: "Paracetamol",
    strength: "650mg",
    category: "Analgesic",
    dosageForm: "Tablet",
    manufacturer: "GSK",
    batchNumber: "CR2547",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    quantity: 850,
    reorderLevel: 200,
    unitPrice: 1.2,
    mrp: 1.8,
    gstPercent: 12,
    expiryDate: "2027-08-15",
  },
  {
    id: "MED-002",
    brandName: "Dolo 650",
    genericName: "Paracetamol",
    strength: "650mg",
    category: "Analgesic",
    dosageForm: "Tablet",
    manufacturer: "Micro Labs",
    batchNumber: "DL3321",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    quantity: 620,
    reorderLevel: 200,
    unitPrice: 1.1,
    mrp: 1.7,
    gstPercent: 12,
    expiryDate: "2027-11-10",
  },
  {
    id: "MED-003",
    brandName: "Brufen 400",
    genericName: "Ibuprofen",
    strength: "400mg",
    category: "Analgesic",
    dosageForm: "Tablet",
    manufacturer: "Abbott",
    batchNumber: "BR8842",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    quantity: 45,
    reorderLevel: 100,
    unitPrice: 2.5,
    mrp: 3.8,
    gstPercent: 12,
    expiryDate: "2026-12-20",
  },
  {
    id: "MED-004",
    brandName: "Mox 500",
    genericName: "Amoxicillin",
    strength: "500mg",
    category: "Antibiotic",
    dosageForm: "Capsule",
    manufacturer: "Sun Pharma",
    batchNumber: "MX1190",
    schedule: "H1",
    storageCondition: "Room Temperature",
    quantity: 0,
    reorderLevel: 150,
    unitPrice: 6.2,
    mrp: 9.5,
    gstPercent: 12,
    expiryDate: "2027-02-28",
  },
  {
    id: "MED-005",
    brandName: "Azithral 500",
    genericName: "Azithromycin",
    strength: "500mg",
    category: "Antibiotic",
    dosageForm: "Tablet",
    manufacturer: "Alembic",
    batchNumber: "AZ4456",
    schedule: "H1",
    storageCondition: "Room Temperature",
    quantity: 90,
    reorderLevel: 100,
    unitPrice: 18.0,
    mrp: 26.0,
    gstPercent: 12,
    expiryDate: "2026-08-05",
  },
  {
    id: "MED-006",
    brandName: "Cifran 500",
    genericName: "Ciprofloxacin",
    strength: "500mg",
    category: "Antibiotic",
    dosageForm: "Tablet",
    manufacturer: "Ranbaxy",
    batchNumber: "CF7723",
    schedule: "H1",
    storageCondition: "Room Temperature",
    quantity: 310,
    reorderLevel: 100,
    unitPrice: 8.5,
    mrp: 12.0,
    gstPercent: 12,
    expiryDate: "2027-05-18",
  },
  {
    id: "MED-007",
    brandName: "Glycomet 500",
    genericName: "Metformin",
    strength: "500mg",
    category: "Antidiabetic",
    dosageForm: "Tablet",
    manufacturer: "USV",
    batchNumber: "GM5612",
    schedule: "H",
    storageCondition: "Room Temperature",
    quantity: 480,
    reorderLevel: 150,
    unitPrice: 1.8,
    mrp: 2.6,
    gstPercent: 12,
    expiryDate: "2027-09-30",
  },
  {
    id: "MED-008",
    brandName: "Amlopres 5",
    genericName: "Amlodipine",
    strength: "5mg",
    category: "Antihypertensive",
    dosageForm: "Tablet",
    manufacturer: "Cipla",
    batchNumber: "AM9981",
    schedule: "H",
    storageCondition: "Room Temperature",
    quantity: 275,
    reorderLevel: 100,
    unitPrice: 2.1,
    mrp: 3.0,
    gstPercent: 12,
    expiryDate: "2027-03-22",
  },
  {
    id: "MED-009",
    brandName: "Atorva 10",
    genericName: "Atorvastatin",
    strength: "10mg",
    category: "Lipid-Lowering",
    dosageForm: "Tablet",
    manufacturer: "Zydus",
    batchNumber: "AT4470",
    schedule: "H",
    storageCondition: "Room Temperature",
    quantity: 198,
    reorderLevel: 100,
    unitPrice: 4.5,
    mrp: 6.8,
    gstPercent: 12,
    expiryDate: "2026-07-19",
  },
  {
    id: "MED-010",
    brandName: "Omez 20",
    genericName: "Omeprazole",
    strength: "20mg",
    category: "Antacid / PPI",
    dosageForm: "Capsule",
    manufacturer: "Dr. Reddy's",
    batchNumber: "OM3320",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    quantity: 410,
    reorderLevel: 150,
    unitPrice: 3.2,
    mrp: 4.9,
    gstPercent: 12,
    expiryDate: "2027-01-12",
  },
  {
    id: "MED-011",
    brandName: "Pan 40",
    genericName: "Pantoprazole",
    strength: "40mg",
    category: "Antacid / PPI",
    dosageForm: "Tablet",
    manufacturer: "Alkem",
    batchNumber: "PN6671",
    schedule: "H",
    storageCondition: "Room Temperature",
    quantity: 22,
    reorderLevel: 100,
    unitPrice: 5.0,
    mrp: 7.5,
    gstPercent: 12,
    expiryDate: "2027-04-08",
  },
  {
    id: "MED-012",
    brandName: "Alerid 10",
    genericName: "Cetirizine",
    strength: "10mg",
    category: "Antihistamine",
    dosageForm: "Tablet",
    manufacturer: "Cipla",
    batchNumber: "CT2280",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    quantity: 560,
    reorderLevel: 150,
    unitPrice: 0.9,
    mrp: 1.5,
    gstPercent: 12,
    expiryDate: "2027-10-25",
  },
  {
    id: "MED-013",
    brandName: "Levocet 5",
    genericName: "Levocetirizine",
    strength: "5mg",
    category: "Antihistamine",
    dosageForm: "Tablet",
    manufacturer: "UCB",
    batchNumber: "LV5543",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    quantity: 0,
    reorderLevel: 100,
    unitPrice: 1.5,
    mrp: 2.3,
    gstPercent: 12,
    expiryDate: "2026-09-14",
  },
  {
    id: "MED-014",
    brandName: "Asthalin Inhaler",
    genericName: "Salbutamol",
    strength: "100mcg/dose",
    category: "Respiratory",
    dosageForm: "Inhaler",
    manufacturer: "Cipla",
    batchNumber: "AS7790",
    schedule: "H",
    storageCondition: "Room Temperature",
    quantity: 38,
    reorderLevel: 40,
    unitPrice: 95.0,
    mrp: 135.0,
    gstPercent: 12,
    expiryDate: "2026-10-30",
  },
  {
    id: "MED-015",
    brandName: "Benadryl Syrup",
    genericName: "Diphenhydramine",
    strength: "100ml",
    category: "Respiratory",
    dosageForm: "Syrup",
    manufacturer: "Johnson & Johnson",
    batchNumber: "BD1123",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    quantity: 130,
    reorderLevel: 50,
    unitPrice: 45.0,
    mrp: 68.0,
    gstPercent: 12,
    expiryDate: "2026-06-10",
  },
  {
    id: "MED-016",
    brandName: "Electral",
    genericName: "Oral Rehydration Salts",
    strength: "21.8g sachet",
    category: "Rehydration",
    dosageForm: "Sachet / Powder",
    manufacturer: "FDC",
    batchNumber: "EL9012",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    quantity: 920,
    reorderLevel: 200,
    unitPrice: 8.0,
    mrp: 12.0,
    gstPercent: 5,
    expiryDate: "2028-01-01",
  },
  {
    id: "MED-017",
    brandName: "Lantus",
    genericName: "Insulin Glargine",
    strength: "100 IU/ml",
    category: "Antidiabetic",
    dosageForm: "Injection",
    manufacturer: "Sanofi",
    batchNumber: "LN3345",
    schedule: "H",
    storageCondition: "Refrigerated (2-8°C)",
    quantity: 18,
    reorderLevel: 20,
    unitPrice: 410.0,
    mrp: 580.0,
    gstPercent: 5,
    expiryDate: "2026-08-31",
  },
  {
    id: "MED-018",
    brandName: "Voveran Gel",
    genericName: "Diclofenac",
    strength: "1%",
    category: "Antiseptic / Topical",
    dosageForm: "Ointment / Gel",
    manufacturer: "Novartis",
    batchNumber: "VV4456",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    quantity: 205,
    reorderLevel: 80,
    unitPrice: 38.0,
    mrp: 55.0,
    gstPercent: 12,
    expiryDate: "2027-06-15",
  },
  {
    id: "MED-019",
    brandName: "Betadine",
    genericName: "Povidone Iodine",
    strength: "5%",
    category: "Antiseptic / Topical",
    dosageForm: "Ointment / Gel",
    manufacturer: "Win-Medicare",
    batchNumber: "BT7781",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    quantity: 165,
    reorderLevel: 60,
    unitPrice: 28.0,
    mrp: 42.0,
    gstPercent: 12,
    expiryDate: "2027-09-01",
  },
  {
    id: "MED-020",
    brandName: "Calcirol Sachet",
    genericName: "Vitamin D3",
    strength: "60,000 IU",
    category: "Vitamin & Supplement",
    dosageForm: "Sachet / Powder",
    manufacturer: "Cadila",
    batchNumber: "CL2290",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    quantity: 340,
    reorderLevel: 100,
    unitPrice: 22.0,
    mrp: 32.0,
    gstPercent: 5,
    expiryDate: "2027-12-20",
  },
  {
    id: "MED-021",
    brandName: "Revital",
    genericName: "Multivitamin & Minerals",
    strength: "—",
    category: "Vitamin & Supplement",
    dosageForm: "Capsule",
    manufacturer: "Ranbaxy",
    batchNumber: "RV5567",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    quantity: 0,
    reorderLevel: 100,
    unitPrice: 8.5,
    mrp: 12.5,
    gstPercent: 18,
    expiryDate: "2027-02-14",
  },
  {
    id: "MED-022",
    brandName: "Fefol",
    genericName: "Iron + Folic Acid",
    strength: "—",
    category: "Vitamin & Supplement",
    dosageForm: "Tablet",
    manufacturer: "Pfizer",
    batchNumber: "FF3398",
    schedule: "OTC",
    storageCondition: "Room Temperature",
    quantity: 290,
    reorderLevel: 100,
    unitPrice: 1.6,
    mrp: 2.4,
    gstPercent: 12,
    expiryDate: "2026-07-05",
  },
  {
    id: "MED-023",
    brandName: "Domstal",
    genericName: "Domperidone",
    strength: "10mg",
    category: "Antiemetic",
    dosageForm: "Tablet",
    manufacturer: "Torrent",
    batchNumber: "DM6612",
    schedule: "H",
    storageCondition: "Room Temperature",
    quantity: 175,
    reorderLevel: 80,
    unitPrice: 2.0,
    mrp: 3.0,
    gstPercent: 12,
    expiryDate: "2027-05-30",
  },
  {
    id: "MED-024",
    brandName: "Emeset",
    genericName: "Ondansetron",
    strength: "4mg",
    category: "Antiemetic",
    dosageForm: "Tablet",
    manufacturer: "Cipla",
    batchNumber: "ON7734",
    schedule: "H",
    storageCondition: "Room Temperature",
    quantity: 0,
    reorderLevel: 60,
    unitPrice: 5.5,
    mrp: 8.0,
    gstPercent: 12,
    expiryDate: "2026-05-20",
  },
  {
    id: "MED-025",
    brandName: "Ultracet",
    genericName: "Tramadol + Paracetamol",
    strength: "37.5mg/325mg",
    category: "Analgesic",
    dosageForm: "Tablet",
    manufacturer: "Johnson & Johnson",
    batchNumber: "UL2245",
    schedule: "H1",
    storageCondition: "Room Temperature",
    quantity: 64,
    reorderLevel: 50,
    unitPrice: 6.0,
    mrp: 9.0,
    gstPercent: 12,
    expiryDate: "2027-01-18",
  },
  {
    id: "MED-026",
    brandName: "Morcontin 10",
    genericName: "Morphine Sulfate",
    strength: "10mg",
    category: "Analgesic",
    dosageForm: "Tablet",
    manufacturer: "Mundipharma",
    batchNumber: "MR1102",
    schedule: "X",
    storageCondition: "Cool & Dry, Secure Storage",
    quantity: 12,
    reorderLevel: 15,
    unitPrice: 22.0,
    mrp: 32.0,
    gstPercent: 12,
    expiryDate: "2027-08-22",
  },
  {
    id: "MED-027",
    brandName: "Alprax 0.25",
    genericName: "Alprazolam",
    strength: "0.25mg",
    category: "Anxiolytic",
    dosageForm: "Tablet",
    manufacturer: "Torrent",
    batchNumber: "AP3367",
    schedule: "X",
    storageCondition: "Cool & Dry, Secure Storage",
    quantity: 55,
    reorderLevel: 40,
    unitPrice: 1.8,
    mrp: 2.7,
    gstPercent: 12,
    expiryDate: "2027-03-10",
  },
];
