export const kpiData = [
  {
    id: 1,
    title: "Total Patients",
    value: "3,842",
    change: "+12.5%",
    trend: "up",
    period: "vs last month",
    color: "#2563eb",
    bg: "#eff6ff",
    icon: "patients",
    trend7d: [310, 295, 340, 328, 355, 370, 362],
  },
  {
    id: 2,
    title: "Today's Appointments",
    value: "128",
    change: "+4.3%",
    trend: "up",
    period: "vs yesterday",
    color: "#7c3aed",
    bg: "#f5f3ff",
    icon: "appointments",
    trend7d: [98, 115, 102, 125, 119, 131, 128],
  },
  {
    id: 3,
    title: "Monthly Revenue",
    value: "₹8,24,500",
    change: "+18.2%",
    trend: "up",
    period: "vs last month",
    color: "#059669",
    bg: "#ecfdf5",
    icon: "revenue",
    trend7d: [620000, 695000, 710000, 688000, 742000, 790000, 824500],
  },
  {
    id: 4,
    title: "Beds Occupied",
    value: "74 / 120",
    change: "-3.1%",
    trend: "down",
    period: "vs last week",
    color: "#d97706",
    bg: "#fffbeb",
    icon: "beds",
    trend7d: [80, 78, 82, 77, 79, 76, 74],
  },
];

// Department Service Summary
export const departmentStats = [
  {
    id: 1,
    label: "OPD",
    fullLabel: "Outpatient Department",
    patientsToday: 128,
    patientsMonth: 1240,
    icon: "🏥",
    color: "#2563eb",
    bg: "#eff6ff",
    serviceMetric: "Avg Wait Time",
    serviceValue: "18 min",
    secondaryMetric: "Consultations Done",
    secondaryValue: "112",
    trend7d: [95, 110, 102, 125, 119, 131, 128],
    note: "Walk-ins welcome",
  },
  {
    id: 2,
    label: "IPD",
    fullLabel: "Inpatient Department",
    patientsToday: 74,
    patientsMonth: 312,
    icon: "🛏️",
    color: "#7c3aed",
    bg: "#f5f3ff",
    serviceMetric: "Avg Stay Duration",
    serviceValue: "4.2 days",
    secondaryMetric: "Recoveries This Month",
    secondaryValue: "89",
    trend7d: [68, 71, 73, 70, 75, 72, 74],
    note: "Beds available: 46",
  },
  {
    id: 3,
    label: "Pharmacy",
    fullLabel: "Pharmacy",
    patientsToday: 156,
    patientsMonth: 3820,
    icon: "💊",
    color: "#059669",
    bg: "#ecfdf5",
    serviceMetric: "Dispensing Time",
    serviceValue: "< 8 min",
    secondaryMetric: "Free Medicine Given",
    secondaryValue: "48 patients",
    trend7d: [130, 145, 138, 152, 148, 160, 156],
    note: "Generic medicines prioritized",
  },
  {
    id: 4,
    label: "Lab",
    fullLabel: "Lab & Diagnostics",
    patientsToday: 43,
    patientsMonth: 890,
    icon: "🧪",
    color: "#d97706",
    bg: "#fffbeb",
    serviceMetric: "Report Turnaround",
    serviceValue: "2.4 hrs",
    secondaryMetric: "Emergency Tests",
    secondaryValue: "12 today",
    trend7d: [35, 40, 38, 44, 41, 46, 43],
    note: "Critical results alerted instantly",
  },
];

// Revenue Chart Data (Line Chart)
export const revenueChartData = {
  labels: [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ],
  datasets: [
    {
      label: "OPD Revenue",
      data: [
        320000, 410000, 380000, 520000, 490000, 610000, 580000, 720000, 680000,
        790000, 824500, 860000,
      ],
      borderColor: "#2563eb",
      backgroundColor: "rgba(37,99,235,0.07)",
      borderWidth: 2.5,
      pointBackgroundColor: "#2563eb",
      pointRadius: 3,
      pointHoverRadius: 6,
      fill: true,
      tension: 0.4,
    },
    {
      label: "IPD Revenue",
      data: [
        180000, 220000, 195000, 280000, 310000, 290000, 340000, 380000, 420000,
        390000, 445000, 510000,
      ],
      borderColor: "#7c3aed",
      backgroundColor: "rgba(124,58,237,0.05)",
      borderWidth: 2.5,
      pointBackgroundColor: "#7c3aed",
      pointRadius: 3,
      pointHoverRadius: 6,
      fill: true,
      tension: 0.4,
    },
  ],
};

// Appointment Chart Data (Doughnut)
export const appointmentChartData = {
  labels: ["OPD", "IPD", "Emergency", "Follow-up"],
  datasets: [
    {
      data: [45, 25, 15, 15],
      backgroundColor: ["#2563eb", "#7c3aed", "#ef4444", "#059669"],
      hoverBackgroundColor: ["#1d4ed8", "#6d28d9", "#dc2626", "#047857"],
      borderWidth: 0,
      hoverOffset: 6,
    },
  ],
};

// Recent Patients
export const recentPatients = [
  {
    id: "P-1042",
    name: "Ramesh Sharma",
    age: 45,
    type: "OPD",
    doctor: "Dr. Priya Mehta",
    status: "Completed",
    time: "09:30 AM",
  },
  {
    id: "P-1041",
    name: "Sunita Verma",
    age: 32,
    type: "IPD",
    doctor: "Dr. Anil Kumar",
    status: "Admitted",
    time: "08:45 AM",
  },
  {
    id: "P-1040",
    name: "Arjun Patel",
    age: 58,
    type: "Emergency",
    doctor: "Dr. Neha Singh",
    status: "Critical",
    time: "08:10 AM",
  },
  {
    id: "P-1039",
    name: "Kavya Reddy",
    age: 27,
    type: "OPD",
    doctor: "Dr. Priya Mehta",
    status: "Waiting",
    time: "07:50 AM",
  },
  {
    id: "P-1038",
    name: "Mohammed Iqbal",
    age: 63,
    type: "Follow-up",
    doctor: "Dr. Ravi Gupta",
    status: "Completed",
    time: "07:20 AM",
  },
  {
    id: "P-1037",
    name: "Anjali Desai",
    age: 41,
    type: "IPD",
    doctor: "Dr. Anil Kumar",
    status: "Admitted",
    time: "Yesterday",
  },
  {
    id: "P-1036",
    name: "Deepak Nair",
    age: 36,
    type: "OPD",
    doctor: "Dr. Ravi Gupta",
    status: "Completed",
    time: "Yesterday",
  },
];

// Quick Stats
export const quickStats = [
  { label: "Surgeries Today", value: "8" },
  { label: "Doctors On Duty", value: "24" },
  { label: "Pharmacy Orders", value: "156" },
  { label: "Lab Tests Pending", value: "43" },
];

// ── Appointment Analytics Data ────────────────────────────────────────────────
//
// All appointment data below is mock/placeholder for the UI.
// In Week 8, each export will be replaced by an Axios call to the HMS API.
// The component that consumes this data will not need to change — only this file.

// Day-wise breakdown for the current week (Mon–Sat).
// Each entry holds counts by appointment type so the bar chart can be stacked
// or grouped without restructuring the data.
export const appointmentsByDay = [
  { day: "Mon", OPD: 45, IPD: 12, Emergency: 8, FollowUp: 15 },
  { day: "Tue", OPD: 52, IPD: 10, Emergency: 6, FollowUp: 18 },
  { day: "Wed", OPD: 48, IPD: 14, Emergency: 11, FollowUp: 20 },
  { day: "Thu", OPD: 61, IPD: 9, Emergency: 7, FollowUp: 22 },
  { day: "Fri", OPD: 55, IPD: 16, Emergency: 9, FollowUp: 17 },
  { day: "Sat", OPD: 38, IPD: 8, Emergency: 5, FollowUp: 14 },
];

// 30-day rolling appointment trend.
// Includes both total and outcome breakdown so we can layer
// a completion area over the total for visual context.
export const appointmentTrend30d = [
  { date: "17 May", total: 88, completed: 74, cancelled: 6 },
  { date: "18 May", total: 95, completed: 80, cancelled: 8 },
  { date: "19 May", total: 82, completed: 71, cancelled: 5 },
  { date: "20 May", total: 104, completed: 90, cancelled: 7 },
  { date: "21 May", total: 98, completed: 85, cancelled: 6 },
  { date: "22 May", total: 110, completed: 96, cancelled: 8 },
  { date: "23 May", total: 76, completed: 66, cancelled: 4 },
  { date: "24 May", total: 91, completed: 78, cancelled: 7 },
  { date: "25 May", total: 103, completed: 89, cancelled: 9 },
  { date: "26 May", total: 97, completed: 84, cancelled: 6 },
  { date: "27 May", total: 115, completed: 100, cancelled: 8 },
  { date: "28 May", total: 108, completed: 93, cancelled: 7 },
  { date: "29 May", total: 122, completed: 106, cancelled: 9 },
  { date: "30 May", total: 79, completed: 68, cancelled: 4 },
  { date: "31 May", total: 94, completed: 81, cancelled: 6 },
  { date: "1 Jun", total: 106, completed: 92, cancelled: 8 },
  { date: "2 Jun", total: 118, completed: 102, cancelled: 9 },
  { date: "3 Jun", total: 99, completed: 86, cancelled: 7 },
  { date: "4 Jun", total: 125, completed: 109, cancelled: 10 },
  { date: "5 Jun", total: 112, completed: 97, cancelled: 8 },
  { date: "6 Jun", total: 130, completed: 113, cancelled: 11 },
  { date: "7 Jun", total: 84, completed: 73, cancelled: 5 },
  { date: "8 Jun", total: 107, completed: 93, cancelled: 7 },
  { date: "9 Jun", total: 119, completed: 104, cancelled: 9 },
  { date: "10 Jun", total: 128, completed: 112, cancelled: 9 },
  { date: "11 Jun", total: 115, completed: 100, cancelled: 8 },
  { date: "12 Jun", total: 134, completed: 117, cancelled: 10 },
  { date: "13 Jun", total: 108, completed: 94, cancelled: 7 },
  { date: "14 Jun", total: 122, completed: 106, cancelled: 9 },
  { date: "15 Jun", total: 128, completed: 112, cancelled: 8 },
];

// Doctor workload for the current month.
// Used in a horizontal bar chart. Sorted descending so the busiest
// doctor appears at the top — more natural to scan.
export const doctorWorkload = [
  { name: "Dr. Priya Mehta", specialty: "General Medicine", appointments: 148 },
  { name: "Dr. Anil Kumar", specialty: "Surgery", appointments: 132 },
  { name: "Dr. Neha Singh", specialty: "Emergency", appointments: 119 },
  { name: "Dr. Ravi Gupta", specialty: "Cardiology", appointments: 104 },
  { name: "Dr. Sunita Rao", specialty: "Gynaecology", appointments: 97 },
  { name: "Dr. Mohammed Ali", specialty: "Orthopaedics", appointments: 88 },
];

// Hourly patient volume — used to identify peak staffing periods.
// Hours outside 8AM–8PM are omitted as the hospital runs outpatient
// services only in this window. Emergency operates 24/7 separately.
export const peakHoursData = [
  { hour: "8 AM", patients: 18 },
  { hour: "9 AM", patients: 42 },
  { hour: "10 AM", patients: 65 },
  { hour: "11 AM", patients: 72 },
  { hour: "12 PM", patients: 58 },
  { hour: "1 PM", patients: 34 },
  { hour: "2 PM", patients: 48 },
  { hour: "3 PM", patients: 61 },
  { hour: "4 PM", patients: 55 },
  { hour: "5 PM", patients: 38 },
  { hour: "6 PM", patients: 24 },
  { hour: "7 PM", patients: 12 },
];

// Appointment outcome distribution — used in the pie/donut chart.
// These four states cover every possible appointment lifecycle.
export const appointmentOutcomes = [
  { name: "Completed", value: 87, color: "#059669" },
  { name: "Pending", value: 8, color: "#d97706" },
  { name: "Cancelled", value: 3, color: "#ef4444" },
  { name: "No-Show", value: 2, color: "#94a3b8" },
];

// Summary KPIs shown in the analytics section header row.
export const appointmentSummary = {
  totalThisWeek: 589,
  vsLastWeek: "+8.2%",
  completionRate: "87%",
  avgWaitTime: "18 min",
  cancellationRate: "3%",
  noShowRate: "2%",
};

// ── Full patient records for the enhanced Dashboard table ─────────────────────
//
// 28 records are sufficient to demonstrate 3-page pagination (10 per page).
// In Week 3, the OPD module will have its own patients API endpoint.
// This data is Dashboard-specific and will be replaced by an API call in Week 8.
export const allPatients = [
  {
    id: "P-1042",
    name: "Ramesh Sharma",
    age: 45,
    gender: "Male",
    type: "OPD",
    doctor: "Dr. Priya Mehta",
    status: "Completed",
    time: "09:30 AM",
    ward: "—",
  },
  {
    id: "P-1041",
    name: "Sunita Verma",
    age: 32,
    gender: "Female",
    type: "IPD",
    doctor: "Dr. Anil Kumar",
    status: "Admitted",
    time: "08:45 AM",
    ward: "B-12",
  },
  {
    id: "P-1040",
    name: "Arjun Patel",
    age: 58,
    gender: "Male",
    type: "Emergency",
    doctor: "Dr. Neha Singh",
    status: "Critical",
    time: "08:10 AM",
    ward: "ICU",
  },
  {
    id: "P-1039",
    name: "Kavya Reddy",
    age: 27,
    gender: "Female",
    type: "OPD",
    doctor: "Dr. Priya Mehta",
    status: "Waiting",
    time: "07:50 AM",
    ward: "—",
  },
  {
    id: "P-1038",
    name: "Mohammed Iqbal",
    age: 63,
    gender: "Male",
    type: "Follow-up",
    doctor: "Dr. Ravi Gupta",
    status: "Completed",
    time: "07:20 AM",
    ward: "—",
  },
  {
    id: "P-1037",
    name: "Anjali Desai",
    age: 41,
    gender: "Female",
    type: "IPD",
    doctor: "Dr. Anil Kumar",
    status: "Admitted",
    time: "Yesterday",
    ward: "C-04",
  },
  {
    id: "P-1036",
    name: "Deepak Nair",
    age: 36,
    gender: "Male",
    type: "OPD",
    doctor: "Dr. Ravi Gupta",
    status: "Completed",
    time: "Yesterday",
    ward: "—",
  },
  {
    id: "P-1035",
    name: "Pooja Iyer",
    age: 29,
    gender: "Female",
    type: "OPD",
    doctor: "Dr. Sunita Rao",
    status: "Completed",
    time: "Yesterday",
    ward: "—",
  },
  {
    id: "P-1034",
    name: "Harish Menon",
    age: 54,
    gender: "Male",
    type: "IPD",
    doctor: "Dr. Neha Singh",
    status: "Admitted",
    time: "Yesterday",
    ward: "A-07",
  },
  {
    id: "P-1033",
    name: "Lakshmi Pillai",
    age: 68,
    gender: "Female",
    type: "Follow-up",
    doctor: "Dr. Priya Mehta",
    status: "Completed",
    time: "Yesterday",
    ward: "—",
  },
  {
    id: "P-1032",
    name: "Vikram Singh",
    age: 44,
    gender: "Male",
    type: "Emergency",
    doctor: "Dr. Neha Singh",
    status: "Completed",
    time: "2 days ago",
    ward: "—",
  },
  {
    id: "P-1031",
    name: "Meena Krishnan",
    age: 38,
    gender: "Female",
    type: "OPD",
    doctor: "Dr. Ravi Gupta",
    status: "Completed",
    time: "2 days ago",
    ward: "—",
  },
  {
    id: "P-1030",
    name: "Rajesh Tiwari",
    age: 52,
    gender: "Male",
    type: "IPD",
    doctor: "Dr. Anil Kumar",
    status: "Discharged",
    time: "2 days ago",
    ward: "—",
  },
  {
    id: "P-1029",
    name: "Nisha Kapoor",
    age: 31,
    gender: "Female",
    type: "OPD",
    doctor: "Dr. Sunita Rao",
    status: "Completed",
    time: "2 days ago",
    ward: "—",
  },
  {
    id: "P-1028",
    name: "Santosh Kumar",
    age: 47,
    gender: "Male",
    type: "Follow-up",
    doctor: "Dr. Mohammed Ali",
    status: "Waiting",
    time: "2 days ago",
    ward: "—",
  },
  {
    id: "P-1027",
    name: "Divya Nambiar",
    age: 25,
    gender: "Female",
    type: "OPD",
    doctor: "Dr. Priya Mehta",
    status: "Completed",
    time: "3 days ago",
    ward: "—",
  },
  {
    id: "P-1026",
    name: "Ashok Pandey",
    age: 60,
    gender: "Male",
    type: "IPD",
    doctor: "Dr. Ravi Gupta",
    status: "Admitted",
    time: "3 days ago",
    ward: "B-09",
  },
  {
    id: "P-1025",
    name: "Geeta Sharma",
    age: 72,
    gender: "Female",
    type: "Emergency",
    doctor: "Dr. Neha Singh",
    status: "Discharged",
    time: "3 days ago",
    ward: "—",
  },
  {
    id: "P-1024",
    name: "Rahul Joshi",
    age: 19,
    gender: "Male",
    type: "OPD",
    doctor: "Dr. Mohammed Ali",
    status: "Completed",
    time: "3 days ago",
    ward: "—",
  },
  {
    id: "P-1023",
    name: "Priya Nair",
    age: 35,
    gender: "Female",
    type: "Follow-up",
    doctor: "Dr. Sunita Rao",
    status: "Completed",
    time: "4 days ago",
    ward: "—",
  },
  {
    id: "P-1022",
    name: "Suresh Babu",
    age: 49,
    gender: "Male",
    type: "IPD",
    doctor: "Dr. Anil Kumar",
    status: "Admitted",
    time: "4 days ago",
    ward: "C-11",
  },
  {
    id: "P-1021",
    name: "Anita Bose",
    age: 56,
    gender: "Female",
    type: "OPD",
    doctor: "Dr. Priya Mehta",
    status: "Completed",
    time: "4 days ago",
    ward: "—",
  },
  {
    id: "P-1020",
    name: "Karthik Rajan",
    age: 33,
    gender: "Male",
    type: "Emergency",
    doctor: "Dr. Neha Singh",
    status: "Completed",
    time: "5 days ago",
    ward: "—",
  },
  {
    id: "P-1019",
    name: "Sudha Pillai",
    age: 64,
    gender: "Female",
    type: "Follow-up",
    doctor: "Dr. Ravi Gupta",
    status: "Completed",
    time: "5 days ago",
    ward: "—",
  },
  {
    id: "P-1018",
    name: "Manoj Gupta",
    age: 41,
    gender: "Male",
    type: "OPD",
    doctor: "Dr. Mohammed Ali",
    status: "Completed",
    time: "5 days ago",
    ward: "—",
  },
  {
    id: "P-1017",
    name: "Rekha Singh",
    age: 28,
    gender: "Female",
    type: "IPD",
    doctor: "Dr. Sunita Rao",
    status: "Discharged",
    time: "6 days ago",
    ward: "—",
  },
  {
    id: "P-1016",
    name: "Venkat Rao",
    age: 57,
    gender: "Male",
    type: "OPD",
    doctor: "Dr. Priya Mehta",
    status: "Completed",
    time: "6 days ago",
    ward: "—",
  },
  {
    id: "P-1015",
    name: "Chitra Menon",
    age: 43,
    gender: "Female",
    type: "Emergency",
    doctor: "Dr. Neha Singh",
    status: "Completed",
    time: "7 days ago",
    ward: "—",
  },
];
