// ─────────────────────────────────────────────────────────────────────────────
// appointmentsData.js
//
// Seed data for the OPD Appointment Module. Each record links to a real
// patient (by id) from opdData.js / PatientsContext — patientName is kept
// denormalized here purely for fast table rendering without a lookup on
// every row, the same way a real API response would typically include it.
// AppointmentsContext.jsx imports this as its initial state.
// ─────────────────────────────────────────────────────────────────────────────

export const STATUS_CONFIG = {
  Scheduled: { color: "#2563eb", bg: "#eff6ff" },
  Completed: { color: "#059669", bg: "#ecfdf5" },
  Cancelled: { color: "#94a3b8", bg: "#f8fafc" },
  "No-Show": { color: "#d97706", bg: "#fffbeb" },
};

export const VISIT_TYPE_CONFIG = {
  OPD: { color: "#2563eb", bg: "#eff6ff" },
  "Follow-up": { color: "#059669", bg: "#ecfdf5" },
  Emergency: { color: "#dc2626", bg: "#fef2f2" },
};

export const initialAppointments = [
  {
    id: "APT-2001",
    patientId: "P-1001",
    patientName: "Ramesh Sharma",
    doctor: "Dr. Priya Mehta",
    date: "2026-06-20",
    time: "09:30",
    visitType: "OPD",
    status: "Scheduled",
    reason: "Routine checkup and BP monitoring",
  },
  {
    id: "APT-2002",
    patientId: "P-1002",
    patientName: "Sunita Verma",
    doctor: "Dr. Anil Kumar",
    date: "2026-06-20",
    time: "10:00",
    visitType: "Follow-up",
    status: "Scheduled",
    reason: "Follow-up on medication dosage",
  },
  {
    id: "APT-2003",
    patientId: "P-1003",
    patientName: "Arjun Patel",
    doctor: "Dr. Neha Singh",
    date: "2026-06-20",
    time: "08:15",
    visitType: "Emergency",
    status: "Completed",
    reason: "Chest pain, urgent evaluation",
  },
  {
    id: "APT-2004",
    patientId: "P-1004",
    patientName: "Kavya Reddy",
    doctor: "Dr. Priya Mehta",
    date: "2026-06-19",
    time: "11:00",
    visitType: "OPD",
    status: "Completed",
    reason: "Annual health screening",
  },
  {
    id: "APT-2005",
    patientId: "P-1005",
    patientName: "Mohammed Iqbal",
    doctor: "Dr. Ravi Gupta",
    date: "2026-06-19",
    time: "14:30",
    visitType: "Follow-up",
    status: "Completed",
    reason: "Post-surgery recovery check",
  },
  {
    id: "APT-2006",
    patientId: "P-1006",
    patientName: "Anjali Desai",
    doctor: "Dr. Anil Kumar",
    date: "2026-06-18",
    time: "09:00",
    visitType: "OPD",
    status: "No-Show",
    reason: "General consultation",
  },
  {
    id: "APT-2007",
    patientId: "P-1007",
    patientName: "Deepak Nair",
    doctor: "Dr. Ravi Gupta",
    date: "2026-06-21",
    time: "10:30",
    visitType: "OPD",
    status: "Scheduled",
    reason: "Skin allergy consultation",
  },
  {
    id: "APT-2008",
    patientId: "P-1008",
    patientName: "Pooja Iyer",
    doctor: "Dr. Sunita Rao",
    date: "2026-06-21",
    time: "11:45",
    visitType: "Follow-up",
    status: "Scheduled",
    reason: "Pregnancy follow-up",
  },
  {
    id: "APT-2009",
    patientId: "P-1009",
    patientName: "Harish Menon",
    doctor: "Dr. Neha Singh",
    date: "2026-06-17",
    time: "15:00",
    visitType: "OPD",
    status: "Completed",
    reason: "Diabetes management review",
  },
  {
    id: "APT-2010",
    patientId: "P-1010",
    patientName: "Lakshmi Pillai",
    doctor: "Dr. Priya Mehta",
    date: "2026-06-22",
    time: "09:15",
    visitType: "Follow-up",
    status: "Scheduled",
    reason: "Knee pain follow-up",
  },
  {
    id: "APT-2011",
    patientId: "P-1011",
    patientName: "Vikram Singh",
    doctor: "Dr. Neha Singh",
    date: "2026-06-16",
    time: "13:00",
    visitType: "Emergency",
    status: "Completed",
    reason: "Accident injury treatment",
  },
  {
    id: "APT-2012",
    patientId: "P-1012",
    patientName: "Meena Krishnan",
    doctor: "Dr. Ravi Gupta",
    date: "2026-06-20",
    time: "16:00",
    visitType: "OPD",
    status: "Scheduled",
    reason: "Cardiology consultation",
  },
  {
    id: "APT-2013",
    patientId: "P-1013",
    patientName: "Rajesh Tiwari",
    doctor: "Dr. Anil Kumar",
    date: "2026-06-15",
    time: "10:00",
    visitType: "OPD",
    status: "Cancelled",
    reason: "General checkup — patient rescheduled",
  },
  {
    id: "APT-2014",
    patientId: "P-1014",
    patientName: "Nisha Kapoor",
    doctor: "Dr. Sunita Rao",
    date: "2026-06-23",
    time: "11:00",
    visitType: "OPD",
    status: "Scheduled",
    reason: "Routine gynaecology visit",
  },
  {
    id: "APT-2015",
    patientId: "P-1015",
    patientName: "Santosh Kumar",
    doctor: "Dr. Mohammed Ali",
    date: "2026-06-14",
    time: "09:30",
    visitType: "Follow-up",
    status: "Completed",
    reason: "Orthopaedic follow-up",
  },
  {
    id: "APT-2016",
    patientId: "P-1016",
    patientName: "Divya Nambiar",
    doctor: "Dr. Priya Mehta",
    date: "2026-06-24",
    time: "14:00",
    visitType: "OPD",
    status: "Scheduled",
    reason: "Migraine evaluation",
  },
  {
    id: "APT-2017",
    patientId: "P-1017",
    patientName: "Ashok Pandey",
    doctor: "Dr. Ravi Gupta",
    date: "2026-06-13",
    time: "10:30",
    visitType: "OPD",
    status: "Completed",
    reason: "Hypertension review",
  },
  {
    id: "APT-2018",
    patientId: "P-1018",
    patientName: "Geeta Sharma",
    doctor: "Dr. Neha Singh",
    date: "2026-06-12",
    time: "08:00",
    visitType: "Emergency",
    status: "Completed",
    reason: "Fall injury assessment",
  },
  {
    id: "APT-2019",
    patientId: "P-1019",
    patientName: "Rahul Joshi",
    doctor: "Dr. Mohammed Ali",
    date: "2026-06-20",
    time: "12:30",
    visitType: "OPD",
    status: "Scheduled",
    reason: "Sports injury consultation",
  },
  {
    id: "APT-2020",
    patientId: "P-1020",
    patientName: "Priya Nair",
    doctor: "Dr. Sunita Rao",
    date: "2026-06-25",
    time: "10:00",
    visitType: "Follow-up",
    status: "Scheduled",
    reason: "Postnatal checkup",
  },
];
