// ─────────────────────────────────────────────────────────────────────────────
// opdData.js
//
// Patient master registry. Deliberately holds ONLY durable facts about a
// person — never anything tied to one specific visit. visitType, doctor,
// and clinical status used to live here, which was a real modeling error:
// those describe a single encounter, not a person. They now live solely on
// the Appointment record (appointmentsData.js) — see AppointmentList.jsx.
// Status here is intentionally just Active/Inactive: "is this still a
// recognized patient of ours," nothing clinical.
// ─────────────────────────────────────────────────────────────────────────────

export const STATUS_CONFIG = {
  Active: { color: "#059669", bg: "#ecfdf5" },
  Inactive: { color: "#94a3b8", bg: "#f8fafc" },
};

export const DOCTORS = [
  "Dr. Priya Mehta",
  "Dr. Anil Kumar",
  "Dr. Neha Singh",
  "Dr. Ravi Gupta",
  "Dr. Sunita Rao",
  "Dr. Mohammed Ali",
];

export const initialPatients = [
  {
    id: "P-1001",
    name: "Ramesh Sharma",
    age: 45,
    gender: "Male",
    phone: "9876543210",
    email: "ramesh.sharma@example.com",
    bloodGroup: "B+",
    address: "Andheri, Mumbai, Maharashtra",
    registeredOn: "2026-01-15",
    status: "Active",
  },
  {
    id: "P-1002",
    name: "Sunita Verma",
    age: 32,
    gender: "Female",
    phone: "9876543211",
    email: "sunita.verma@example.com",
    bloodGroup: "O+",
    address: "Karol Bagh, Delhi",
    registeredOn: "2026-01-18",
    status: "Active",
  },
  {
    id: "P-1003",
    name: "Arjun Patel",
    age: 58,
    gender: "Male",
    phone: "9876543212",
    email: "arjun.patel@example.com",
    bloodGroup: "A-",
    address: "Navrangpura, Ahmedabad",
    registeredOn: "2026-01-20",
    status: "Active",
  },
  {
    id: "P-1004",
    name: "Kavya Reddy",
    age: 27,
    gender: "Female",
    phone: "9876543213",
    email: "kavya.reddy@example.com",
    bloodGroup: "AB+",
    address: "Banjara Hills, Hyderabad",
    registeredOn: "2026-01-22",
    status: "Active",
  },
  {
    id: "P-1005",
    name: "Mohammed Iqbal",
    age: 63,
    gender: "Male",
    phone: "9876543214",
    email: "iqbal.m@example.com",
    bloodGroup: "O-",
    address: "Park Circus, Kolkata",
    registeredOn: "2026-01-25",
    status: "Active",
  },
  {
    id: "P-1006",
    name: "Anjali Desai",
    age: 41,
    gender: "Female",
    phone: "9876543215",
    email: "anjali.desai@example.com",
    bloodGroup: "B-",
    address: "Satellite, Ahmedabad",
    registeredOn: "2026-01-28",
    status: "Inactive",
  },
  {
    id: "P-1007",
    name: "Deepak Nair",
    age: 36,
    gender: "Male",
    phone: "9876543216",
    email: "deepak.nair@example.com",
    bloodGroup: "A+",
    address: "Kochi, Kerala",
    registeredOn: "2026-02-01",
    status: "Active",
  },
  {
    id: "P-1008",
    name: "Pooja Iyer",
    age: 29,
    gender: "Female",
    phone: "9876543217",
    email: "pooja.iyer@example.com",
    bloodGroup: "O+",
    address: "T Nagar, Chennai",
    registeredOn: "2026-02-03",
    status: "Active",
  },
  {
    id: "P-1009",
    name: "Harish Menon",
    age: 54,
    gender: "Male",
    phone: "9876543218",
    email: "harish.menon@example.com",
    bloodGroup: "B+",
    address: "Indiranagar, Bengaluru",
    registeredOn: "2026-02-05",
    status: "Active",
  },
  {
    id: "P-1010",
    name: "Lakshmi Pillai",
    age: 68,
    gender: "Female",
    phone: "9876543219",
    email: "lakshmi.pillai@example.com",
    bloodGroup: "AB-",
    address: "Mylapore, Chennai",
    registeredOn: "2026-02-08",
    status: "Active",
  },
  {
    id: "P-1011",
    name: "Vikram Singh",
    age: 44,
    gender: "Male",
    phone: "9876543220",
    email: "vikram.singh@example.com",
    bloodGroup: "O+",
    address: "Civil Lines, Jaipur",
    registeredOn: "2026-02-10",
    status: "Active",
  },
  {
    id: "P-1012",
    name: "Meena Krishnan",
    age: 38,
    gender: "Female",
    phone: "9876543221",
    email: "meena.krishnan@example.com",
    bloodGroup: "A+",
    address: "Adyar, Chennai",
    registeredOn: "2026-02-12",
    status: "Active",
  },
  {
    id: "P-1013",
    name: "Rajesh Tiwari",
    age: 52,
    gender: "Male",
    phone: "9876543222",
    email: "rajesh.tiwari@example.com",
    bloodGroup: "B+",
    address: "Gomti Nagar, Lucknow",
    registeredOn: "2026-02-14",
    status: "Active",
  },
  {
    id: "P-1014",
    name: "Nisha Kapoor",
    age: 31,
    gender: "Female",
    phone: "9876543223",
    email: "nisha.kapoor@example.com",
    bloodGroup: "O-",
    address: "Sector 17, Chandigarh",
    registeredOn: "2026-02-16",
    status: "Active",
  },
  {
    id: "P-1015",
    name: "Santosh Kumar",
    age: 47,
    gender: "Male",
    phone: "9876543224",
    email: "santosh.kumar@example.com",
    bloodGroup: "AB+",
    address: "Boring Road, Patna",
    registeredOn: "2026-02-18",
    status: "Inactive",
  },
  {
    id: "P-1016",
    name: "Divya Nambiar",
    age: 25,
    gender: "Female",
    phone: "9876543225",
    email: "divya.nambiar@example.com",
    bloodGroup: "B-",
    address: "Panampilly Nagar, Kochi",
    registeredOn: "2026-02-20",
    status: "Active",
  },
  {
    id: "P-1017",
    name: "Ashok Pandey",
    age: 60,
    gender: "Male",
    phone: "9876543226",
    email: "ashok.pandey@example.com",
    bloodGroup: "O+",
    address: "Vasant Kunj, Delhi",
    registeredOn: "2026-02-22",
    status: "Active",
  },
  {
    id: "P-1018",
    name: "Geeta Sharma",
    age: 72,
    gender: "Female",
    phone: "9876543227",
    email: "geeta.sharma@example.com",
    bloodGroup: "A+",
    address: "Malviya Nagar, Jaipur",
    registeredOn: "2026-02-25",
    status: "Active",
  },
  {
    id: "P-1019",
    name: "Rahul Joshi",
    age: 19,
    gender: "Male",
    phone: "9876543228",
    email: "rahul.joshi@example.com",
    bloodGroup: "B+",
    address: "Kothrud, Pune",
    registeredOn: "2026-02-27",
    status: "Active",
  },
  {
    id: "P-1020",
    name: "Priya Nair",
    age: 35,
    gender: "Female",
    phone: "9876543229",
    email: "priya.nair@example.com",
    bloodGroup: "O-",
    address: "Vyttila, Kochi",
    registeredOn: "2026-03-01",
    status: "Active",
  },
  {
    id: "P-1021",
    name: "Suresh Babu",
    age: 49,
    gender: "Male",
    phone: "9876543230",
    email: "suresh.babu@example.com",
    bloodGroup: "AB+",
    address: "Velachery, Chennai",
    registeredOn: "2026-03-03",
    status: "Active",
  },
  {
    id: "P-1022",
    name: "Anita Bose",
    age: 56,
    gender: "Female",
    phone: "9876543231",
    email: "anita.bose@example.com",
    bloodGroup: "A-",
    address: "Salt Lake, Kolkata",
    registeredOn: "2026-03-05",
    status: "Active",
  },
  {
    id: "P-1023",
    name: "Karthik Rajan",
    age: 33,
    gender: "Male",
    phone: "9876543232",
    email: "karthik.rajan@example.com",
    bloodGroup: "O+",
    address: "Anna Nagar, Chennai",
    registeredOn: "2026-03-08",
    status: "Active",
  },
  {
    id: "P-1024",
    name: "Sudha Pillai",
    age: 64,
    gender: "Female",
    phone: "9876543233",
    email: "sudha.pillai@example.com",
    bloodGroup: "B+",
    address: "Fort Kochi, Kerala",
    registeredOn: "2026-03-10",
    status: "Active",
  },
  {
    id: "P-1025",
    name: "Manoj Gupta",
    age: 41,
    gender: "Male",
    phone: "9876543234",
    email: "manoj.gupta@example.com",
    bloodGroup: "O-",
    address: "Hazratganj, Lucknow",
    registeredOn: "2026-03-12",
    status: "Active",
  },
  {
    id: "P-1026",
    name: "Rekha Singh",
    age: 28,
    gender: "Female",
    phone: "9876543235",
    email: "rekha.singh@example.com",
    bloodGroup: "AB-",
    address: "Mahanagar, Lucknow",
    registeredOn: "2026-03-15",
    status: "Inactive",
  },
  {
    id: "P-1027",
    name: "Venkat Rao",
    age: 57,
    gender: "Male",
    phone: "9876543236",
    email: "venkat.rao@example.com",
    bloodGroup: "B+",
    address: "Jubilee Hills, Hyderabad",
    registeredOn: "2026-03-18",
    status: "Active",
  },
  {
    id: "P-1028",
    name: "Chitra Menon",
    age: 43,
    gender: "Female",
    phone: "9876543237",
    email: "chitra.menon@example.com",
    bloodGroup: "A+",
    address: "Edappally, Kochi",
    registeredOn: "2026-03-20",
    status: "Active",
  },
  {
    id: "P-1029",
    name: "Ramesh Iyer",
    age: 39,
    gender: "Male",
    phone: "9876543238",
    email: "ramesh.iyer@example.com",
    bloodGroup: "O+",
    address: "Besant Nagar, Chennai",
    registeredOn: "2026-03-22",
    status: "Active",
  },
  {
    id: "P-1030",
    name: "Shalini Bhatt",
    age: 30,
    gender: "Female",
    phone: "9876543239",
    email: "shalini.bhatt@example.com",
    bloodGroup: "B-",
    address: "C-Scheme, Jaipur",
    registeredOn: "2026-03-25",
    status: "Active",
  },
  {
    id: "P-1031",
    name: "Gopal Krishnan",
    age: 66,
    gender: "Male",
    phone: "9876543240",
    email: "gopal.krishnan@example.com",
    bloodGroup: "A-",
    address: "Thrissur, Kerala",
    registeredOn: "2026-03-28",
    status: "Active",
  },
  {
    id: "P-1032",
    name: "Swati Joshi",
    age: 26,
    gender: "Female",
    phone: "9876543241",
    email: "swati.joshi@example.com",
    bloodGroup: "O-",
    address: "Aundh, Pune",
    registeredOn: "2026-03-30",
    status: "Active",
  },
];
